import DashboardLayout from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, Check, Crown, Gamepad2, Link2, Plus, Shield, UserPlus, Users } from "lucide-react";
import { useState } from "react";
import { Link } from "wouter";
import { toast } from "sonner";

export default function TeamDashboard() {
  const { data: teams, isLoading } = trpc.teams.mine.useQuery();
  const utils = trpc.useUtils();
  const createTeam = trpc.teams.create.useMutation({ onSuccess: () => utils.teams.mine.invalidate() });
  const [showCreate, setShowCreate] = useState(false);
  const [form, setForm] = useState({ name: "", tag: "", game: "VALORANT", region: "SEA", description: "" });
  const team = teams?.[0];

  return <DashboardLayout><div className="min-h-screen px-5 py-8 text-white sm:px-8 lg:px-12"><div className="mx-auto max-w-[1200px] space-y-8"><header className="flex flex-col justify-between gap-5 border-b border-white/[0.08] pb-7 sm:flex-row sm:items-end"><div><Link href="/dashboard/player"><Button variant="ghost" className="mb-5 -ml-3 gap-2 px-3 text-xs text-white/40 hover:bg-white/[0.05] hover:text-white"><ArrowLeft className="h-3.5 w-3.5" />Back to overview</Button></Link><p className="text-[10px] font-bold uppercase tracking-[0.24em] text-lime-300">Team operations / captain view</p><h1 className="mt-3 text-4xl font-semibold tracking-[-0.05em]">Build the roster that <span className="text-lime-300">holds the line.</span></h1><p className="mt-3 max-w-xl text-sm leading-6 text-white/45">Invite players, lock lineups, and keep your tournament identity sharp across every bracket.</p></div><Button onClick={() => setShowCreate(true)} className="bg-lime-300 text-black hover:bg-lime-200"><Plus className="mr-2 h-4 w-4" />Create team</Button></header>

{isLoading ? <div className="rounded-2xl border border-white/10 p-8 text-white/45">Loading your roster…</div> : team ? <><div className="grid gap-5 lg:grid-cols-[1fr_0.45fr]"><Card className="overflow-hidden border-lime-300/20 bg-[linear-gradient(120deg,rgba(190,242,100,0.12),rgba(255,255,255,0.02)_58%)]"><CardContent className="relative min-h-[240px] p-7"><div className="absolute -right-10 -top-20 h-64 w-64 rounded-full bg-lime-300/10 blur-3xl" /><div className="relative flex items-start justify-between"><div className="flex items-center gap-4"><div className="grid h-16 w-16 place-items-center rounded-2xl bg-lime-300 text-lg font-black text-black shadow-[0_0_40px_rgba(190,242,100,0.15)]">{team.tag.slice(0, 3)}</div><div><p className="text-2xl font-semibold">{team.name}</p><p className="mt-1 text-sm text-white/45">{team.tag} <span className="mx-1 text-white/20">/</span> {team.game} <span className="mx-1 text-white/20">/</span> {team.region}</p></div></div><Badge className="border-lime-300/20 bg-lime-300/10 text-lime-200">ACTIVE</Badge></div><p className="relative mt-10 max-w-lg text-sm leading-6 text-white/55">{team.description || "Your roster has a clear signal. Add a sharp description so opponents know what they are stepping into."}</p><div className="relative mt-7 flex flex-wrap gap-2"><Badge className="border-white/10 bg-black/10 text-white/45"><Gamepad2 className="mr-1.5 h-3 w-3" />{team.game}</Badge><Badge className="border-white/10 bg-black/10 text-white/45"><Shield className="mr-1.5 h-3 w-3" />SEA region</Badge><Badge onClick={() => toast.info("Clan linking is staged", { description: "Clan affiliation management will unlock with the next roster service pass." })} className="cursor-pointer border-white/10 bg-black/10 text-white/45 hover:bg-white/10"><Link2 className="mr-1.5 h-3 w-3" />Link clan</Badge></div></CardContent></Card><Card className="border-white/[0.08] bg-white/[0.025]"><CardHeader className="px-6 pb-2 pt-6"><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-white/30">Lineup readiness</p><CardTitle className="mt-2 text-4xl font-semibold text-lime-300">80%</CardTitle></CardHeader><CardContent className="px-6 pb-6"><div className="h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full w-4/5 rounded-full bg-lime-300" /></div><p className="mt-4 text-sm leading-6 text-white/45">Four of five active slots are confirmed for the next tournament window.</p><Button onClick={() => toast.success("Lineup lock requested", { description: "Your captain confirmation is queued for the next tournament sync." })} variant="outline" className="mt-5 w-full border-white/10 bg-transparent text-white/60 hover:bg-white/[0.06]">Lock lineup</Button></CardContent></Card></div>

<div className="grid gap-5 xl:grid-cols-[1fr_0.6fr]"><Card className="border-white/[0.08] bg-white/[0.025]"><CardHeader className="flex flex-row items-center justify-between border-b border-white/[0.07] px-6 py-5"><div><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-lime-300">Active roster</p><CardTitle className="mt-2 text-xl">Five seats, one signal</CardTitle></div><Button onClick={() => toast.info("Invite flow ready", { description: "Copy an invite link from the roster invite service when it is connected." })} variant="ghost" className="text-xs text-white/50 hover:bg-white/[0.05] hover:text-white"><UserPlus className="mr-2 h-3.5 w-3.5" />Invite player</Button></CardHeader><CardContent className="p-0">{["NOVA_PLAYER", "Kinetic", "Rook", "Mira", "Open slot"].map((name, index) => <div key={name} className="flex items-center gap-4 border-b border-white/[0.06] px-6 py-4 last:border-0"><div className={`grid h-10 w-10 place-items-center rounded-xl text-xs font-black ${name === "Open slot" ? "border border-dashed border-white/15 text-white/20" : index === 0 ? "bg-lime-300 text-black" : "bg-white/[0.08] text-white/55"}`}>{name === "Open slot" ? "+" : name.slice(0, 2)}</div><div className="min-w-0 flex-1"><p className={`text-sm font-semibold ${name === "Open slot" ? "text-white/25" : "text-white/80"}`}>{name}</p><p className="mt-1 text-xs text-white/35">{name === "Open slot" ? "Recruit a player" : index === 0 ? "Captain · verified" : "Player · active"}</p></div>{name !== "Open slot" && (index === 0 ? <Badge onClick={() => toast.info("Captain role", { description: "Captain permissions are managed from the roster service." })} className="cursor-pointer border-lime-300/20 bg-lime-300/10 text-lime-300"><Crown className="mr-1 h-3 w-3" />Captain</Badge> : <Badge className="border-white/10 bg-white/[0.04] text-white/35">Ready</Badge>)}</div>)}</CardContent></Card><Card className="border-white/[0.08] bg-white/[0.025]"><CardHeader className="px-6 pb-2 pt-6"><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-white/30">Team checklist</p><CardTitle className="mt-2 text-xl">Before lock-in</CardTitle></CardHeader><CardContent className="space-y-3 px-6 pb-6">{["Confirm all player handles", "Connect clan affiliation", "Review tournament rules", "Submit lineup before deadline"].map((item, index) => <div key={item} className="flex items-center gap-3 rounded-xl border border-white/[0.07] bg-white/[0.025] p-3 text-sm text-white/60"><span className={`grid h-5 w-5 place-items-center rounded-full ${index < 2 ? "bg-lime-300 text-black" : "border border-white/15 text-white/20"}`}>{index < 2 ? <Check className="h-3 w-3" /> : index + 1}</span>{item}</div>)}</CardContent></Card></div></> : <EmptyTeam onCreate={() => setShowCreate(true)} />}

{showCreate && <div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-5 backdrop-blur-sm"><Card className="w-full max-w-lg border-white/10 bg-[#101510] text-white"><CardHeader><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-lime-300">New team</p><CardTitle className="mt-2 text-2xl">Set the identity</CardTitle></CardHeader><CardContent><form className="space-y-4" onSubmit={event => { event.preventDefault(); createTeam.mutate(form, { onSuccess: () => setShowCreate(false) }); }}><div className="grid gap-4 sm:grid-cols-[1fr_120px]"><div><Label className="text-white/55">Team name</Label><Input required value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} className="mt-2 border-white/10 bg-white/[0.04] text-white" placeholder="Null Sector" /></div><div><Label className="text-white/55">Tag</Label><Input required value={form.tag} onChange={event => setForm({ ...form, tag: event.target.value.toUpperCase() })} className="mt-2 border-white/10 bg-white/[0.04] text-white" placeholder="NSEC" /></div></div><div><Label className="text-white/55">Primary game</Label><Input required value={form.game} onChange={event => setForm({ ...form, game: event.target.value })} className="mt-2 border-white/10 bg-white/[0.04] text-white" /></div><div><Label className="text-white/55">Description</Label><Input value={form.description} onChange={event => setForm({ ...form, description: event.target.value })} className="mt-2 border-white/10 bg-white/[0.04] text-white" placeholder="The line we hold." /></div><div className="flex justify-end gap-2 pt-3"><Button type="button" variant="ghost" onClick={() => setShowCreate(false)} className="text-white/50">Cancel</Button><Button disabled={createTeam.isPending} type="submit" className="bg-lime-300 text-black hover:bg-lime-200">{createTeam.isPending ? "Creating…" : "Create team"}</Button></div></form></CardContent></Card></div>}</div></div></DashboardLayout>;
}

function EmptyTeam({ onCreate }: { onCreate: () => void }) { return <div className="rounded-3xl border border-dashed border-white/15 bg-white/[0.02] p-12 text-center"><Users className="mx-auto h-10 w-10 text-lime-300" /><h2 className="mt-5 text-2xl font-semibold">No active roster yet.</h2><p className="mx-auto mt-3 max-w-md text-sm leading-6 text-white/45">Create a team to unlock captain tools, lineup lock, and tournament registration.</p><Button onClick={onCreate} className="mt-7 bg-lime-300 text-black hover:bg-lime-200"><Plus className="mr-2 h-4 w-4" />Create your first team</Button></div>; }
