-- Phase 4: integration-ready sponsor, commerce, and analytics contracts.
-- This migration stores metadata only. Provider credentials and payment processing remain external.

create table if not exists public.sponsors (
  id bigint generated by default as identity primary key,
  name text not null,
  mark text not null,
  website_url text,
  tier text not null default 'partner' check (tier in ('presenting', 'partner', 'supporting')),
  active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.sponsor_campaigns (
  id bigint generated by default as identity primary key,
  sponsor_id bigint not null references public.sponsors(id) on delete cascade,
  tournament_id bigint references public.tournaments(id) on delete set null,
  clan_id bigint references public.clans(id) on delete set null,
  placement text not null check (placement in ('tournament', 'bracket', 'clan', 'landing')),
  headline text not null,
  body text,
  cta_label text,
  cta_url text,
  starts_at timestamptz,
  ends_at timestamptz,
  active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  clan_id bigint references public.clans(id) on delete set null,
  sku text not null unique,
  name text not null,
  description text,
  category text not null check (category in ('jersey', 'hoodie', 'accessory', 'digital')),
  price_cents integer not null check (price_cents >= 0),
  currency char(3) not null default 'USD',
  image_url text,
  inventory_label text,
  active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete restrict,
  status text not null default 'draft' check (status in ('draft', 'pending_checkout', 'paid', 'cancelled', 'refunded')),
  currency char(3) not null default 'USD',
  subtotal_cents integer not null default 0 check (subtotal_cents >= 0),
  total_cents integer not null default 0 check (total_cents >= 0),
  provider_reference text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.order_items (
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete restrict,
  quantity integer not null check (quantity between 1 and 99),
  unit_price_cents integer not null check (unit_price_cents >= 0),
  variant_label text,
  primary key (order_id, product_id, variant_label)
);

create table if not exists public.integration_connections (
  id bigint generated by default as identity primary key,
  provider text not null check (provider in ('discord', 'twitch')),
  clan_id bigint references public.clans(id) on delete cascade,
  tournament_id bigint references public.tournaments(id) on delete cascade,
  external_id text,
  display_name text,
  status text not null default 'disconnected' check (status in ('ready', 'pending', 'disconnected', 'error')),
  created_by bigint not null references public.users(id) on delete restrict,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  check (num_nonnulls(clan_id, tournament_id) = 1)
);

create table if not exists public.analytics_snapshots (
  id bigint generated by default as identity primary key,
  scope text not null check (scope in ('platform', 'tournament', 'clan', 'stream')),
  tournament_id bigint references public.tournaments(id) on delete cascade,
  clan_id bigint references public.clans(id) on delete cascade,
  metric_key text not null,
  metric_value numeric not null,
  captured_at timestamptz not null default timezone('utc', now()),
  check (scope = 'platform' or num_nonnulls(tournament_id, clan_id) <= 1)
);

create index if not exists sponsor_campaigns_active_idx on public.sponsor_campaigns(active, starts_at, ends_at);
create index if not exists products_active_category_idx on public.products(active, category);
create index if not exists orders_user_created_idx on public.orders(user_id, created_at desc);
create index if not exists integration_connections_scope_idx on public.integration_connections(provider, clan_id, tournament_id);
create index if not exists analytics_snapshots_scope_metric_idx on public.analytics_snapshots(scope, metric_key, captured_at desc);

drop trigger if exists sponsors_set_updated_at on public.sponsors;
create trigger sponsors_set_updated_at before update on public.sponsors for each row execute function public.set_updated_at();
drop trigger if exists sponsor_campaigns_set_updated_at on public.sponsor_campaigns;
create trigger sponsor_campaigns_set_updated_at before update on public.sponsor_campaigns for each row execute function public.set_updated_at();
drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at before update on public.products for each row execute function public.set_updated_at();
drop trigger if exists orders_set_updated_at on public.orders;
create trigger orders_set_updated_at before update on public.orders for each row execute function public.set_updated_at();
drop trigger if exists integration_connections_set_updated_at on public.integration_connections;
create trigger integration_connections_set_updated_at before update on public.integration_connections for each row execute function public.set_updated_at();

alter table public.sponsors enable row level security;
alter table public.sponsor_campaigns enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.integration_connections enable row level security;
alter table public.analytics_snapshots enable row level security;

create policy sponsors_read_authenticated on public.sponsors for select to authenticated using (active or public.is_admin());
create policy sponsor_campaigns_read_authenticated on public.sponsor_campaigns for select to authenticated using (active or public.is_admin());
create policy products_read_authenticated on public.products for select to authenticated using (active or public.is_admin());
create policy orders_read_own on public.orders for select to authenticated using (user_id = public.current_user_id() or public.is_admin());
create policy order_items_read_own on public.order_items for select to authenticated using (order_id in (select id from public.orders where user_id = public.current_user_id()) or public.is_admin());
create policy integrations_read_owner_or_admin on public.integration_connections for select to authenticated using (
  public.is_admin()
  or clan_id in (select id from public.clans where owner_id = public.current_user_id())
  or tournament_id in (select id from public.tournaments where created_by = public.current_user_id())
);
create policy analytics_read_admin on public.analytics_snapshots for select to authenticated using (public.is_admin());
