-- Phase 5: full platform backend.
-- Apply AFTER 20260820000000_meno_arena.sql and 20260820010000_phase4.sql
-- (Supabase Dashboard -> SQL Editor). Every statement is idempotent.

-- ---------------------------------------------------------------------------
-- Roles & identity
-- ---------------------------------------------------------------------------
alter table public.users drop constraint if exists users_role_check;
alter table public.users add constraint users_role_check check (role in ('user', 'admin', 'organizer', 'sponsor'));
alter table public.users add column if not exists avatar_url text;

alter table public.player_profiles add column if not exists avatar_url text;
alter table public.player_profiles add column if not exists banner_url text;
alter table public.player_profiles add column if not exists socials jsonb not null default '{}'::jsonb;

-- ---------------------------------------------------------------------------
-- Teams: branding, captaincy, lineup lock, invites
-- ---------------------------------------------------------------------------
alter table public.teams add column if not exists logo_url text;
alter table public.teams add column if not exists banner_url text;
alter table public.teams add column if not exists socials jsonb not null default '{}'::jsonb;
alter table public.teams add column if not exists captain_id bigint references public.users(id) on delete set null;
alter table public.teams add column if not exists lineup_locked_at timestamptz;
alter table public.teams add column if not exists wins integer not null default 0 check (wins >= 0);
alter table public.teams add column if not exists losses integer not null default 0 check (losses >= 0);

update public.teams set captain_id = owner_id where captain_id is null;

create table if not exists public.team_invites (
  id bigint generated by default as identity primary key,
  team_id bigint not null references public.teams(id) on delete cascade,
  invited_user_id bigint references public.users(id) on delete cascade,
  invited_email text,
  invited_by bigint not null references public.users(id) on delete cascade,
  role text not null default 'player' check (role in ('captain', 'player', 'manager')),
  status text not null default 'pending' check (status in ('pending', 'accepted', 'declined', 'revoked')),
  message text,
  created_at timestamptz not null default timezone('utc', now()),
  responded_at timestamptz,
  check (num_nonnulls(invited_user_id, invited_email) = 1)
);
create index if not exists team_invites_team_status_idx on public.team_invites(team_id, status);
create index if not exists team_invites_user_status_idx on public.team_invites(invited_user_id, status);
create index if not exists team_invites_email_idx on public.team_invites(lower(invited_email));

-- ---------------------------------------------------------------------------
-- Clans: branding, verification, followers, invites, achievements
-- ---------------------------------------------------------------------------
alter table public.clans add column if not exists logo_url text;
alter table public.clans add column if not exists banner_url text;
alter table public.clans add column if not exists verified boolean not null default false;
alter table public.clans add column if not exists follower_count integer not null default 0 check (follower_count >= 0);
alter table public.clans add column if not exists prize_earnings_cents bigint not null default 0 check (prize_earnings_cents >= 0);
alter table public.clans add column if not exists trophies integer not null default 0 check (trophies >= 0);
alter table public.clans add column if not exists social_links jsonb not null default '{}'::jsonb;

create table if not exists public.clan_followers (
  clan_id bigint not null references public.clans(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now()),
  primary key (clan_id, user_id)
);

create table if not exists public.clan_invites (
  id bigint generated by default as identity primary key,
  clan_id bigint not null references public.clans(id) on delete cascade,
  team_id bigint references public.teams(id) on delete cascade,
  user_id bigint references public.users(id) on delete cascade,
  invited_by bigint not null references public.users(id) on delete cascade,
  role text not null default 'member' check (role in ('owner', 'manager', 'scout', 'member')),
  status text not null default 'pending' check (status in ('pending', 'accepted', 'declined', 'revoked')),
  message text,
  created_at timestamptz not null default timezone('utc', now()),
  responded_at timestamptz,
  check (num_nonnulls(team_id, user_id) = 1)
);
create index if not exists clan_invites_clan_status_idx on public.clan_invites(clan_id, status);

create table if not exists public.clan_achievements (
  id bigint generated by default as identity primary key,
  clan_id bigint not null references public.clans(id) on delete cascade,
  tournament_id bigint references public.tournaments(id) on delete set null,
  team_id bigint references public.teams(id) on delete set null,
  title text not null,
  placement integer check (placement >= 1),
  prize_cents bigint not null default 0 check (prize_cents >= 0),
  achieved_at timestamptz not null default timezone('utc', now())
);
create index if not exists clan_achievements_clan_idx on public.clan_achievements(clan_id, achieved_at desc);

create or replace function public.sync_clan_follower_count()
returns trigger
language plpgsql
as $$
begin
  if tg_op = 'INSERT' then
    update public.clans set follower_count = follower_count + 1 where id = new.clan_id;
  elsif tg_op = 'DELETE' then
    update public.clans set follower_count = greatest(follower_count - 1, 0) where id = old.clan_id;
  end if;
  return null;
end;
$$;
drop trigger if exists clan_followers_sync_count on public.clan_followers;
create trigger clan_followers_sync_count after insert or delete on public.clan_followers for each row execute function public.sync_clan_follower_count();

-- ---------------------------------------------------------------------------
-- Tournaments: lifecycle, check-in windows, prize split, seeding
-- ---------------------------------------------------------------------------
alter table public.tournaments drop constraint if exists tournaments_status_check;
alter table public.tournaments add constraint tournaments_status_check check (status in ('draft', 'registration', 'checkin', 'live', 'completed', 'cancelled'));
alter table public.tournaments add column if not exists description text;
alter table public.tournaments add column if not exists banner_url text;
alter table public.tournaments add column if not exists checkin_opens_at timestamptz;
alter table public.tournaments add column if not exists best_of integer not null default 1 check (best_of in (1, 3, 5, 7));
alter table public.tournaments add column if not exists prize_split jsonb not null default '[60, 30, 10]'::jsonb;
alter table public.tournaments add column if not exists sponsor_contribution_cents integer not null default 0 check (sponsor_contribution_cents >= 0);
alter table public.tournaments add column if not exists discord_url text;
alter table public.tournaments add column if not exists region text;
alter table public.tournaments add column if not exists bracket_published_at timestamptz;

alter table public.tournament_registrations add column if not exists checked_in_at timestamptz;
alter table public.tournament_registrations add column if not exists seed integer;
alter table public.tournament_registrations add column if not exists payment_id bigint;
create index if not exists registrations_tournament_status_idx on public.tournament_registrations(tournament_id, status);

-- ---------------------------------------------------------------------------
-- Matches: multi-bracket support, advancement links, streams
-- ---------------------------------------------------------------------------
alter table public.matches add column if not exists bracket text not null default 'winners' check (bracket in ('winners', 'losers', 'grand_final', 'round_robin', 'swiss'));
alter table public.matches drop constraint if exists matches_tournament_id_round_position_key;
create unique index if not exists matches_tournament_bracket_round_position_key on public.matches(tournament_id, bracket, round, position);
alter table public.matches add column if not exists best_of integer not null default 1 check (best_of in (1, 3, 5, 7));
alter table public.matches add column if not exists stream_url text;
alter table public.matches add column if not exists next_match_id bigint references public.matches(id) on delete set null;
alter table public.matches add column if not exists next_match_slot text check (next_match_slot in ('home', 'away'));
alter table public.matches add column if not exists loser_next_match_id bigint references public.matches(id) on delete set null;
alter table public.matches add column if not exists loser_next_match_slot text check (loser_next_match_slot in ('home', 'away'));
alter table public.matches add column if not exists completed_at timestamptz;

alter table public.match_reports add column if not exists opponent_team_id bigint references public.teams(id) on delete set null;
alter table public.match_reports add column if not exists confirmed_by bigint references public.users(id) on delete set null;
alter table public.match_reports add column if not exists confirmed_at timestamptz;

-- ---------------------------------------------------------------------------
-- Payments (sandbox) and prize payouts
-- ---------------------------------------------------------------------------
create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete restrict,
  kind text not null check (kind in ('entry_fee', 'order')),
  tournament_id bigint references public.tournaments(id) on delete set null,
  team_id bigint references public.teams(id) on delete set null,
  order_id bigint,
  amount_cents integer not null check (amount_cents >= 0),
  currency char(3) not null default 'USD',
  status text not null check (status in ('pending', 'succeeded', 'failed', 'refunded')) default 'pending',
  provider text not null default 'sandbox',
  reference text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);
create index if not exists payments_user_created_idx on public.payments(user_id, created_at desc);
create index if not exists payments_tournament_idx on public.payments(tournament_id);
drop trigger if exists payments_set_updated_at on public.payments;
create trigger payments_set_updated_at before update on public.payments for each row execute function public.set_updated_at();

create table if not exists public.prize_payouts (
  id bigint generated by default as identity primary key,
  tournament_id bigint not null references public.tournaments(id) on delete cascade,
  team_id bigint references public.teams(id) on delete set null,
  placement integer not null check (placement >= 1),
  share_percent numeric(5, 2) not null check (share_percent >= 0 and share_percent <= 100),
  amount_cents bigint not null default 0 check (amount_cents >= 0),
  status text not null default 'pending' check (status in ('pending', 'processing', 'paid')),
  paid_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (tournament_id, placement)
);
drop trigger if exists prize_payouts_set_updated_at on public.prize_payouts;
create trigger prize_payouts_set_updated_at before update on public.prize_payouts for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Announcements
-- ---------------------------------------------------------------------------
create table if not exists public.announcements (
  id bigint generated by default as identity primary key,
  tournament_id bigint references public.tournaments(id) on delete cascade,
  author_id bigint not null references public.users(id) on delete restrict,
  title text not null,
  body text not null,
  pinned boolean not null default false,
  created_at timestamptz not null default timezone('utc', now())
);
create index if not exists announcements_tournament_idx on public.announcements(tournament_id, pinned desc, created_at desc);

-- ---------------------------------------------------------------------------
-- Notifications: widen kinds
-- ---------------------------------------------------------------------------
alter table public.notifications drop constraint if exists notifications_kind_check;
alter table public.notifications add constraint notifications_kind_check check (kind in (
  'match_start', 'checkin', 'result', 'dispute', 'admin_decision', 'payout',
  'team_invite', 'clan_invite', 'clan_roster', 'tournament', 'team', 'system'
));

-- ---------------------------------------------------------------------------
-- Media gallery
-- ---------------------------------------------------------------------------
alter table public.media_assets add column if not exists kind text not null default 'highlight' check (kind in ('short', 'reel', 'highlight', 'meme', 'reaction', 'promo'));
alter table public.media_assets add column if not exists tags text[] not null default '{}';
alter table public.media_assets add column if not exists views integer not null default 0 check (views >= 0);
alter table public.media_assets add column if not exists likes integer not null default 0 check (likes >= 0);
alter table public.media_assets add column if not exists duration_seconds integer check (duration_seconds >= 0);
alter table public.media_assets add column if not exists published boolean not null default true;
alter table public.media_assets add column if not exists clan_id bigint references public.clans(id) on delete set null;

create table if not exists public.media_likes (
  media_id bigint not null references public.media_assets(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now()),
  primary key (media_id, user_id)
);

create or replace function public.sync_media_like_count()
returns trigger
language plpgsql
as $$
begin
  if tg_op = 'INSERT' then
    update public.media_assets set likes = likes + 1 where id = new.media_id;
  elsif tg_op = 'DELETE' then
    update public.media_assets set likes = greatest(likes - 1, 0) where id = old.media_id;
  end if;
  return null;
end;
$$;
drop trigger if exists media_likes_sync_count on public.media_likes;
create trigger media_likes_sync_count after insert or delete on public.media_likes for each row execute function public.sync_media_like_count();

-- ---------------------------------------------------------------------------
-- Phase 4 tables: sponsor tone/logo, product images, integration webhooks
-- ---------------------------------------------------------------------------
alter table public.sponsors add column if not exists logo_url text;
alter table public.sponsors add column if not exists tone text not null default 'lime' check (tone in ('lime', 'steel', 'amber'));
alter table public.sponsors add column if not exists clan_id bigint references public.clans(id) on delete set null;
alter table public.products add column if not exists badge text;
alter table public.products add column if not exists color text;
alter table public.products add column if not exists org_label text;
alter table public.integration_connections add column if not exists webhook_url text;
alter table public.integration_connections add column if not exists role_mapping jsonb not null default '{}'::jsonb;

-- ---------------------------------------------------------------------------
-- Storage buckets
-- ---------------------------------------------------------------------------
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  ('avatars', 'avatars', true, 2097152, array['image/jpeg', 'image/png', 'image/webp']),
  ('team-assets', 'team-assets', true, 3145728, array['image/jpeg', 'image/png', 'image/webp']),
  ('clan-assets', 'clan-assets', true, 4194304, array['image/jpeg', 'image/png', 'image/webp']),
  ('match-proof', 'match-proof', true, 6291456, array['image/jpeg', 'image/png', 'image/webp']),
  ('media', 'media', true, 26214400, array['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'video/mp4', 'video/webm'])
on conflict (id) do nothing;

-- ---------------------------------------------------------------------------
-- Row level security for new tables (server writes use the service role)
-- ---------------------------------------------------------------------------
alter table public.team_invites enable row level security;
alter table public.clan_followers enable row level security;
alter table public.clan_invites enable row level security;
alter table public.clan_achievements enable row level security;
alter table public.payments enable row level security;
alter table public.prize_payouts enable row level security;
alter table public.announcements enable row level security;
alter table public.media_likes enable row level security;

drop policy if exists team_invites_read_involved on public.team_invites;
create policy team_invites_read_involved on public.team_invites for select to authenticated using (
  invited_user_id = public.current_user_id() or invited_by = public.current_user_id()
  or team_id in (select id from public.teams where owner_id = public.current_user_id()) or public.is_admin()
);
drop policy if exists clan_followers_read_all on public.clan_followers;
create policy clan_followers_read_all on public.clan_followers for select to authenticated using (true);
drop policy if exists clan_followers_manage_own on public.clan_followers;
create policy clan_followers_manage_own on public.clan_followers for all to authenticated using (user_id = public.current_user_id()) with check (user_id = public.current_user_id());
drop policy if exists clan_invites_read_involved on public.clan_invites;
create policy clan_invites_read_involved on public.clan_invites for select to authenticated using (
  user_id = public.current_user_id() or invited_by = public.current_user_id()
  or clan_id in (select id from public.clans where owner_id = public.current_user_id()) or public.is_admin()
);
drop policy if exists clan_achievements_read_all on public.clan_achievements;
create policy clan_achievements_read_all on public.clan_achievements for select to authenticated using (true);
drop policy if exists payments_read_own on public.payments;
create policy payments_read_own on public.payments for select to authenticated using (user_id = public.current_user_id() or public.is_admin());
drop policy if exists prize_payouts_read_all on public.prize_payouts;
create policy prize_payouts_read_all on public.prize_payouts for select to authenticated using (true);
drop policy if exists announcements_read_all on public.announcements;
create policy announcements_read_all on public.announcements for select to authenticated using (true);
drop policy if exists media_likes_read_all on public.media_likes;
create policy media_likes_read_all on public.media_likes for select to authenticated using (true);
drop policy if exists media_likes_manage_own on public.media_likes;
create policy media_likes_manage_own on public.media_likes for all to authenticated using (user_id = public.current_user_id()) with check (user_id = public.current_user_id());

-- Public (anonymous) read access for the discovery surfaces served by the client without a session.
drop policy if exists tournaments_read_anon on public.tournaments;
create policy tournaments_read_anon on public.tournaments for select to anon using (status <> 'draft');
drop policy if exists matches_read_anon on public.matches;
create policy matches_read_anon on public.matches for select to anon using (true);
drop policy if exists teams_read_anon on public.teams;
create policy teams_read_anon on public.teams for select to anon using (true);
drop policy if exists clans_read_anon on public.clans;
create policy clans_read_anon on public.clans for select to anon using (true);

-- ---------------------------------------------------------------------------
-- Realtime
-- ---------------------------------------------------------------------------
do $$
begin
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and tablename = 'match_reports') then
    alter publication supabase_realtime add table public.match_reports;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and tablename = 'announcements') then
    alter publication supabase_realtime add table public.announcements;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and tablename = 'tournament_registrations') then
    alter publication supabase_realtime add table public.tournament_registrations;
  end if;
end $$;
