-- Meno Arena Supabase foundation
-- Apply once in Supabase Dashboard -> SQL Editor.
-- This migration is intentionally additive and does not alter the existing MySQL schema.

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  supabase_user_id uuid not null unique references auth.users(id) on delete cascade,
  name text,
  email text,
  role text not null default 'user' check (role in ('user', 'admin')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  last_signed_in timestamptz not null default timezone('utc', now())
);

create table if not exists public.player_profiles (
  id bigint generated by default as identity primary key,
  user_id bigint not null unique references public.users(id) on delete cascade,
  handle text not null,
  bio text,
  region text,
  primary_game text,
  wins integer not null default 0 check (wins >= 0),
  losses integer not null default 0 check (losses >= 0),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  owner_id bigint not null references public.users(id) on delete restrict,
  name text not null,
  tag text not null,
  game text not null,
  region text,
  description text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.team_members (
  team_id bigint not null references public.teams(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  role text not null default 'player' check (role in ('captain', 'player', 'manager')),
  joined_at timestamptz not null default timezone('utc', now()),
  primary key (team_id, user_id)
);

create table if not exists public.clans (
  id bigint generated by default as identity primary key,
  owner_id bigint not null references public.users(id) on delete restrict,
  name text not null,
  tag text not null,
  region text,
  bio text,
  founded_year integer check (founded_year between 1900 and 2100),
  socials text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.clan_teams (
  clan_id bigint not null references public.clans(id) on delete cascade,
  team_id bigint not null references public.teams(id) on delete cascade,
  added_at timestamptz not null default timezone('utc', now()),
  primary key (clan_id, team_id)
);

create table if not exists public.clan_members (
  clan_id bigint not null references public.clans(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  role text not null default 'member' check (role in ('owner', 'manager', 'scout', 'member')),
  joined_at timestamptz not null default timezone('utc', now()),
  primary key (clan_id, user_id)
);

create table if not exists public.tournaments (
  id bigint generated by default as identity primary key,
  name text not null,
  game text not null,
  format text not null default 'single_elimination' check (format in ('single_elimination', 'double_elimination', 'round_robin', 'swiss')),
  status text not null default 'registration' check (status in ('registration', 'live', 'completed')),
  starts_at timestamptz not null,
  registration_closes_at timestamptz,
  prize_pool_cents integer not null default 0 check (prize_pool_cents >= 0),
  entry_fee_cents integer not null default 0 check (entry_fee_cents >= 0),
  max_teams integer not null default 16 check (max_teams between 2 and 256),
  rules text,
  sponsor_name text,
  stream_url text,
  clan_eligible boolean not null default false,
  created_by bigint not null references public.users(id) on delete restrict,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.tournament_registrations (
  id bigint generated by default as identity primary key,
  tournament_id bigint not null references public.tournaments(id) on delete cascade,
  team_id bigint not null references public.teams(id) on delete cascade,
  registered_by bigint not null references public.users(id) on delete restrict,
  status text not null default 'pending' check (status in ('pending', 'confirmed', 'checked_in', 'withdrawn')),
  accepted_rules_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (tournament_id, team_id)
);

create table if not exists public.matches (
  id bigint generated by default as identity primary key,
  tournament_id bigint not null references public.tournaments(id) on delete cascade,
  round integer not null,
  position integer not null,
  home_team_id bigint references public.teams(id) on delete set null,
  away_team_id bigint references public.teams(id) on delete set null,
  home_score integer not null default 0 check (home_score >= 0),
  away_score integer not null default 0 check (away_score >= 0),
  status text not null default 'upcoming' check (status in ('upcoming', 'live', 'waiting', 'disputed', 'completed')),
  scheduled_at timestamptz,
  winner_team_id bigint references public.teams(id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (tournament_id, round, position)
);

create table if not exists public.match_reports (
  id bigint generated by default as identity primary key,
  match_id bigint not null references public.matches(id) on delete cascade,
  submitted_by bigint not null references public.users(id) on delete restrict,
  team_id bigint not null references public.teams(id) on delete restrict,
  score_for integer not null check (score_for >= 0),
  score_against integer not null check (score_against >= 0),
  screenshot_url text,
  notes text,
  status text not null default 'submitted' check (status in ('submitted', 'waiting_confirmation', 'confirmed', 'disputed', 'admin_resolved')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.disputes (
  id bigint generated by default as identity primary key,
  match_id bigint not null references public.matches(id) on delete cascade,
  opened_by bigint not null references public.users(id) on delete restrict,
  reason text not null,
  status text not null default 'open' check (status in ('open', 'under_review', 'resolved')),
  admin_decision text,
  winner_team_id bigint references public.teams(id) on delete set null,
  resolved_by bigint references public.users(id) on delete set null,
  resolved_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  kind text not null check (kind in ('match_start', 'dispute', 'tournament', 'team', 'system')),
  title text not null,
  body text not null,
  href text,
  read_at timestamptz,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.media_assets (
  id bigint generated by default as identity primary key,
  uploaded_by bigint not null references public.users(id) on delete restrict,
  title text not null,
  description text,
  asset_url text not null,
  thumbnail_url text,
  game text,
  tournament_id bigint references public.tournaments(id) on delete set null,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists teams_owner_id_idx on public.teams(owner_id);
create index if not exists clans_owner_id_idx on public.clans(owner_id);
create index if not exists tournaments_status_starts_at_idx on public.tournaments(status, starts_at);
create index if not exists matches_tournament_id_idx on public.matches(tournament_id);
create index if not exists notifications_user_id_read_at_idx on public.notifications(user_id, read_at);
create index if not exists media_assets_created_at_idx on public.media_assets(created_at desc);

-- Keep updated_at values consistent for mutable entities.
drop trigger if exists users_set_updated_at on public.users;
create trigger users_set_updated_at before update on public.users for each row execute function public.set_updated_at();
drop trigger if exists player_profiles_set_updated_at on public.player_profiles;
create trigger player_profiles_set_updated_at before update on public.player_profiles for each row execute function public.set_updated_at();
drop trigger if exists teams_set_updated_at on public.teams;
create trigger teams_set_updated_at before update on public.teams for each row execute function public.set_updated_at();
drop trigger if exists clans_set_updated_at on public.clans;
create trigger clans_set_updated_at before update on public.clans for each row execute function public.set_updated_at();
drop trigger if exists tournaments_set_updated_at on public.tournaments;
create trigger tournaments_set_updated_at before update on public.tournaments for each row execute function public.set_updated_at();
drop trigger if exists registrations_set_updated_at on public.tournament_registrations;
create trigger registrations_set_updated_at before update on public.tournament_registrations for each row execute function public.set_updated_at();
drop trigger if exists matches_set_updated_at on public.matches;
create trigger matches_set_updated_at before update on public.matches for each row execute function public.set_updated_at();
drop trigger if exists reports_set_updated_at on public.match_reports;
create trigger reports_set_updated_at before update on public.match_reports for each row execute function public.set_updated_at();
drop trigger if exists disputes_set_updated_at on public.disputes;
create trigger disputes_set_updated_at before update on public.disputes for each row execute function public.set_updated_at();

alter table public.users enable row level security;
alter table public.player_profiles enable row level security;
alter table public.teams enable row level security;
alter table public.team_members enable row level security;
alter table public.clans enable row level security;
alter table public.clan_teams enable row level security;
alter table public.clan_members enable row level security;
alter table public.tournaments enable row level security;
alter table public.tournament_registrations enable row level security;
alter table public.matches enable row level security;
alter table public.match_reports enable row level security;
alter table public.disputes enable row level security;
alter table public.notifications enable row level security;
alter table public.media_assets enable row level security;

create or replace function public.current_user_id()
returns bigint
language sql
stable
security definer
set search_path = public
as $$
  select id from public.users where supabase_user_id = auth.uid();
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (select 1 from public.users where supabase_user_id = auth.uid() and role = 'admin');
$$;

-- User rows are self-readable; inserts are performed by the authenticated app flow.
drop policy if exists users_select_own on public.users;
create policy users_select_own on public.users for select to authenticated using (supabase_user_id = auth.uid() or public.is_admin());
drop policy if exists users_insert_self on public.users;
create policy users_insert_self on public.users for insert to authenticated with check (supabase_user_id = auth.uid());
drop policy if exists users_update_self on public.users;
create policy users_update_self on public.users for update to authenticated using (supabase_user_id = auth.uid() or public.is_admin()) with check (supabase_user_id = auth.uid() or public.is_admin());

-- Profiles, teams, clans, tournaments, and media are readable to signed-in users.
create policy player_profiles_read_authenticated on public.player_profiles for select to authenticated using (true);
create policy player_profiles_write_own on public.player_profiles for all to authenticated using (user_id = public.current_user_id() or public.is_admin()) with check (user_id = public.current_user_id() or public.is_admin());
create policy teams_read_authenticated on public.teams for select to authenticated using (true);
create policy teams_write_owner on public.teams for all to authenticated using (owner_id = public.current_user_id() or public.is_admin()) with check (owner_id = public.current_user_id() or public.is_admin());
create policy team_members_read_authenticated on public.team_members for select to authenticated using (true);
create policy team_members_manage_owner on public.team_members for all to authenticated using (team_id in (select id from public.teams where owner_id = public.current_user_id()) or public.is_admin()) with check (team_id in (select id from public.teams where owner_id = public.current_user_id()) or public.is_admin());
create policy clans_read_authenticated on public.clans for select to authenticated using (true);
create policy clans_write_owner on public.clans for all to authenticated using (owner_id = public.current_user_id() or public.is_admin()) with check (owner_id = public.current_user_id() or public.is_admin());
create policy clan_members_read_authenticated on public.clan_members for select to authenticated using (true);
create policy clan_members_manage_owner on public.clan_members for all to authenticated using (clan_id in (select id from public.clans where owner_id = public.current_user_id()) or public.is_admin()) with check (clan_id in (select id from public.clans where owner_id = public.current_user_id()) or public.is_admin());
create policy clan_teams_read_authenticated on public.clan_teams for select to authenticated using (true);
create policy clan_teams_manage_owner on public.clan_teams for all to authenticated using (clan_id in (select id from public.clans where owner_id = public.current_user_id()) or public.is_admin()) with check (clan_id in (select id from public.clans where owner_id = public.current_user_id()) or public.is_admin());
create policy tournaments_read_authenticated on public.tournaments for select to authenticated using (true);
create policy tournaments_write_creator on public.tournaments for all to authenticated using (created_by = public.current_user_id() or public.is_admin()) with check (created_by = public.current_user_id() or public.is_admin());
create policy registrations_read_authenticated on public.tournament_registrations for select to authenticated using (true);
create policy registrations_write_registered_user on public.tournament_registrations for all to authenticated using (registered_by = public.current_user_id() or public.is_admin()) with check (registered_by = public.current_user_id() or public.is_admin());
create policy matches_read_authenticated on public.matches for select to authenticated using (true);
create policy matches_manage_admin on public.matches for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy reports_read_authenticated on public.match_reports for select to authenticated using (true);
create policy reports_write_submitter on public.match_reports for all to authenticated using (submitted_by = public.current_user_id() or public.is_admin()) with check (submitted_by = public.current_user_id() or public.is_admin());
create policy disputes_read_involved_or_admin on public.disputes for select to authenticated using (opened_by = public.current_user_id() or public.is_admin());
create policy disputes_write_opener_or_admin on public.disputes for all to authenticated using (opened_by = public.current_user_id() or public.is_admin()) with check (opened_by = public.current_user_id() or public.is_admin());
create policy notifications_read_own on public.notifications for select to authenticated using (user_id = public.current_user_id() or public.is_admin());
create policy notifications_update_own on public.notifications for update to authenticated using (user_id = public.current_user_id() or public.is_admin()) with check (user_id = public.current_user_id() or public.is_admin());
create policy media_read_authenticated on public.media_assets for select to authenticated using (true);
create policy media_write_uploader on public.media_assets for all to authenticated using (uploaded_by = public.current_user_id() or public.is_admin()) with check (uploaded_by = public.current_user_id() or public.is_admin());

-- Realtime is intentionally enabled for live match and notification surfaces.
alter publication supabase_realtime add table public.matches;
alter publication supabase_realtime add table public.notifications;
